FROM registry.svc.ci.openshift.org/openshift/release:golang-1.13
ENV PKG=/go/src/github.com/openshift/osde2e/
WORKDIR ${PKG}

# compile test binary
ADD . ${PKG}

# install build prerequisites
RUN yum -y update && yum -y install make golang-glide git

# resolve and install imports
ADD glide.yaml glide.lock ${PKG}
RUN glide install --strip-vendor

RUN make check

RUN make out/osde2e
